/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VoxCraftPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// audio.ts
var MicRecorder = class {
  constructor(onPcm, onLevel = null, targetRate = 16e3) {
    this.ctx = null;
    this.stream = null;
    this.source = null;
    this.processor = null;
    this.onPcm = onPcm;
    this.onLevel = onLevel;
    this.targetRate = targetRate;
  }
  get active() {
    return this.ctx !== null;
  }
  async start() {
    if (this.ctx)
      return;
    this.stream = await navigator.mediaDevices.getUserMedia({
      audio: {
        channelCount: 1,
        echoCancellation: true,
        noiseSuppression: true,
        autoGainControl: true
      }
    });
    this.ctx = new AudioContext();
    this.source = this.ctx.createMediaStreamSource(this.stream);
    this.processor = this.ctx.createScriptProcessor(4096, 1, 1);
    const inputRate = this.ctx.sampleRate;
    this.processor.onaudioprocess = (ev) => {
      const input = ev.inputBuffer.getChannelData(0);
      if (this.onLevel)
        this.onLevel(rms(input));
      const down = downsample(input, inputRate, this.targetRate);
      this.onPcm(floatToPcm16(down));
    };
    this.source.connect(this.processor);
    const mute = this.ctx.createGain();
    mute.gain.value = 0;
    this.processor.connect(mute);
    mute.connect(this.ctx.destination);
  }
  async stop() {
    if (this.processor) {
      this.processor.disconnect();
      this.processor.onaudioprocess = null;
      this.processor = null;
    }
    if (this.source) {
      this.source.disconnect();
      this.source = null;
    }
    if (this.stream) {
      this.stream.getTracks().forEach((t) => t.stop());
      this.stream = null;
    }
    if (this.ctx) {
      await this.ctx.close();
      this.ctx = null;
    }
  }
};
function rms(input) {
  let sum = 0;
  for (let i = 0; i < input.length; i++)
    sum += input[i] * input[i];
  return Math.sqrt(sum / input.length);
}
function downsample(input, inRate, outRate) {
  if (outRate >= inRate)
    return input;
  const ratio = inRate / outRate;
  const outLen = Math.floor(input.length / ratio);
  const out = new Float32Array(outLen);
  for (let i = 0; i < outLen; i++) {
    const pos = i * ratio;
    const idx = Math.floor(pos);
    const frac = pos - idx;
    const a = input[idx];
    const b = idx + 1 < input.length ? input[idx + 1] : a;
    out[i] = a + (b - a) * frac;
  }
  return out;
}
function floatToPcm16(input) {
  const buf = new ArrayBuffer(input.length * 2);
  const view = new DataView(buf);
  for (let i = 0; i < input.length; i++) {
    let s = Math.max(-1, Math.min(1, input[i]));
    s = s < 0 ? s * 32768 : s * 32767;
    view.setInt16(i * 2, s, true);
  }
  return buf;
}

// commands.ts
var STOP = ["\u5165\u529B\u7D42\u4E86", "\u97F3\u58F0\u5165\u529B\u7D42\u4E86", "\u7D42\u4E86", "\u30B9\u30C8\u30C3\u30D7"];
var UNDO = ["\u53D6\u308A\u6D88\u3057", "\u53D6\u6D88", "\u4E00\u6587\u524A\u9664", "\u4ECA\u306E\u3092\u524A\u9664", "\u5143\u306B\u623B\u3057\u3066"];
var NEWLINE = ["\u6539\u884C", "\u6B21\u306E\u884C"];
var RECONVERT = ["\u5909\u63DB\u623B\u3057", "\u5909\u63DB\u3057\u76F4\u3057", "\u5909\u63DB\u3084\u308A\u76F4\u3057", "\u518D\u5909\u63DB"];
var REPLACE_RE = /^(.+?)を(.+?)に(?:修正|変換|直して|してください|変えて)$/;
var PICK_RE = /^(?:候補)?([0-9０-９一二三四五六七八九十]+)\s*番?$/;
var KANJI_NUM = {
  \u4E00: 1,
  \u4E8C: 2,
  \u4E09: 3,
  \u56DB: 4,
  \u4E94: 5,
  \u516D: 6,
  \u4E03: 7,
  \u516B: 8,
  \u4E5D: 9,
  \u5341: 10
};
function normalize(text) {
  return text.trim().replace(/[。、．，\s]+$/u, "");
}
function toNumber(token) {
  const zen = token.replace(
    /[０-９]/g,
    (c) => String.fromCharCode(c.charCodeAt(0) - 65248)
  );
  if (/^[0-9]+$/.test(zen))
    return parseInt(zen, 10);
  if (token in KANJI_NUM)
    return KANJI_NUM[token];
  return null;
}
function parseCommand(rawText, prefix = "") {
  let text = normalize(rawText);
  if (prefix) {
    const p = normalize(prefix);
    if (!text.startsWith(p))
      return null;
    text = normalize(text.slice(p.length).replace(/^[、,\s]+/u, ""));
  }
  if (STOP.includes(text))
    return { kind: "stop" };
  if (UNDO.includes(text))
    return { kind: "undo" };
  if (NEWLINE.includes(text))
    return { kind: "newline" };
  if (RECONVERT.includes(text))
    return { kind: "reconvert" };
  const pick = text.match(PICK_RE);
  if (pick) {
    const n = toNumber(pick[1]);
    if (n !== null)
      return { kind: "pick", index: n };
  }
  const rep = text.match(REPLACE_RE);
  if (rep) {
    const from = rep[1].trim();
    const to = rep[2].trim();
    if (from && to)
      return { kind: "replace", from, to };
  }
  return null;
}

// suggest.ts
var import_obsidian = require("obsidian");
var ReconvertModal = class extends import_obsidian.Modal {
  constructor(app, segments, onSubmit) {
    super(app);
    // 各文節で選択中の候補 index
    this.activeSeg = 0;
    this.segEls = [];
    this.segments = segments;
    this.selection = segments.map(() => 0);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("voxcraft-reconvert");
    contentEl.createEl("h3", { text: "\u5909\u63DB\u623B\u3057 \u2014 \u5019\u88DC\u3092\u9078\u629E" });
    contentEl.createEl("p", {
      cls: "voxcraft-hint",
      text: "\u30AF\u30EA\u30C3\u30AF / \u6570\u5B57\u30AD\u30FC / \u97F3\u58F0\u300C3\u756A\u300D\u3067\u9078\u629E\u3002\u6587\u7BC0\u306FTab\u3067\u79FB\u52D5\u3002"
    });
    this.segments.forEach((seg, si) => {
      const segEl = contentEl.createDiv({ cls: "voxcraft-seg" });
      segEl.createSpan({ cls: "voxcraft-reading", text: seg.reading });
      const list = segEl.createDiv({ cls: "voxcraft-cands" });
      seg.candidates.forEach((cand, ci) => {
        const btn = list.createEl("button", {
          cls: "voxcraft-cand",
          text: `${ci + 1}. ${cand}`
        });
        btn.onclick = () => {
          this.activeSeg = si;
          this.choose(ci);
        };
      });
      this.segEls.push(segEl);
      this.paintSeg(si);
    });
    new import_obsidian.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u78BA\u5B9A").setCta().onClick(() => this.submit())
    ).addButton((b) => b.setButtonText("\u30AD\u30E3\u30F3\u30BB\u30EB").onClick(() => this.close()));
    this.scope.register([], "Enter", () => {
      this.submit();
      return false;
    });
    for (let n = 1; n <= 9; n++) {
      this.scope.register([], String(n), () => {
        this.choose(n - 1);
        return false;
      });
    }
    this.scope.register([], "Tab", () => {
      this.activeSeg = (this.activeSeg + 1) % this.segments.length;
      this.highlightActive();
      return false;
    });
  }
  // 音声「N番」からの選択（1始まり）を外部から呼べる。
  pickByVoice(oneBased) {
    this.choose(oneBased - 1);
  }
  choose(ci) {
    const seg = this.segments[this.activeSeg];
    if (!seg || ci < 0 || ci >= seg.candidates.length)
      return;
    this.selection[this.activeSeg] = ci;
    this.paintSeg(this.activeSeg);
  }
  paintSeg(si) {
    const segEl = this.segEls[si];
    if (!segEl)
      return;
    const btns = Array.from(segEl.querySelectorAll(".voxcraft-cand"));
    btns.forEach((b, ci) => {
      b.toggleClass("is-selected", ci === this.selection[si]);
    });
    this.highlightActive();
  }
  highlightActive() {
    this.segEls.forEach(
      (el, i) => el.toggleClass("is-active", i === this.activeSeg)
    );
  }
  submit() {
    const chosen = this.segments.map((seg, i) => seg.candidates[this.selection[i]]);
    this.close();
    this.onSubmit(chosen);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "ws://localhost:8760/ws",
  stripJaAlnumSpace: true,
  symbolDictation: true,
  enableCommands: true,
  commandPrefix: "",
  autoReconvertLast: true
};
var VoxCraftSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VoxCraft \u97F3\u58F0\u5165\u529B" });
    new import_obsidian2.Setting(containerEl).setName("\u8A8D\u8B58\u30B5\u30FC\u30D0\u30FC URL").setDesc(
      "\u81EA\u5B85PC\u3067\u52D5\u304F\u8A8D\u8B58\u30B5\u30FC\u30D0\u30FC\u306E WebSocket \u30A2\u30C9\u30EC\u30B9\u3002Desktop \u306F ws://localhost:8760/ws\u3001Android \u306F ws://<Tailscale\u306EPC IP>:8760/ws\u3002"
    ).addText(
      (t) => t.setPlaceholder("ws://localhost:8760/ws").setValue(this.plugin.settings.serverUrl).onChange(async (v) => {
        this.plugin.settings.serverUrl = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u82F1\u6570\u5B57\u307E\u308F\u308A\u306E\u534A\u89D2\u30B9\u30DA\u30FC\u30B9\u3092\u9664\u53BB").setDesc("\u65E5\u672C\u8A9E\u3068\u82F1\u6570\u5B57\u306E\u9593\u306B\u52DD\u624B\u306B\u5165\u308B\u534A\u89D2\u30B9\u30DA\u30FC\u30B9\u3092\u53D6\u308A\u9664\u304F\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.stripJaAlnumSpace).onChange(async (v) => {
        this.plugin.settings.stripJaAlnumSpace = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u8A18\u53F7\u306E\u8AAD\u307F\u4E0A\u3052\u5909\u63DB").setDesc("\u300C\u307E\u308B\u300D\u2192\u3002\u3001\u300C\u3066\u3093\u300D\u2192\u3001\u3001\u300C\u304B\u3044\u304E\u3087\u3046\u300D\u2192\u6539\u884C \u306A\u3069\u3092\u5909\u63DB\u3059\u308B\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.symbolDictation).onChange(async (v) => {
        this.plugin.settings.symbolDictation = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u97F3\u58F0\u30B3\u30DE\u30F3\u30C9\u3092\u6709\u52B9\u5316").setDesc("\u300C\u53D6\u308A\u6D88\u3057\u300D\u300C\u5909\u63DB\u623B\u3057\u300D\u300CA\u3092B\u306B\u4FEE\u6B63\u300D\u300C\u5165\u529B\u7D42\u4E86\u300D\u7B49\u3092\u8A8D\u8B58\u3059\u308B\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.enableCommands).onChange(async (v) => {
        this.plugin.settings.enableCommands = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u30B3\u30DE\u30F3\u30C9\u306E\u30D7\u30EC\u30D5\u30A3\u30C3\u30AF\u30B9\u8A9E").setDesc(
      "\u8AA4\u7206\u3092\u9632\u3050\u305F\u3081\u3001\u3053\u306E\u8A9E\u3067\u59CB\u307E\u308B\u767A\u8A71\u3060\u3051\u3092\u30B3\u30DE\u30F3\u30C9\u3068\u3057\u3066\u6271\u3046\uFF08\u4F8B:\u300C\u30B3\u30DE\u30F3\u30C9\u300D\uFF09\u3002\u7A7A\u6B04\u306A\u3089\u767A\u8A71\u5168\u4F53\u304C\u30B3\u30DE\u30F3\u30C9\u6587\u306E\u3068\u304D\u306B\u5224\u5B9A\u3002"
    ).addText(
      (t) => t.setPlaceholder("\uFF08\u7A7A\u6B04\u53EF\uFF09").setValue(this.plugin.settings.commandPrefix).onChange(async (v) => {
        this.plugin.settings.commandPrefix = v.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};

// ws.ts
var AsrSocket = class {
  constructor(url, handlers) {
    this.ws = null;
    this.url = url;
    this.handlers = handlers;
  }
  get connected() {
    return this.ws !== null && this.ws.readyState === WebSocket.OPEN;
  }
  connect() {
    return new Promise((resolve, reject) => {
      try {
        this.ws = new WebSocket(this.url);
      } catch (e) {
        reject(e);
        return;
      }
      this.ws.binaryType = "arraybuffer";
      const timer = window.setTimeout(() => {
        reject(new Error("\u63A5\u7D9A\u30BF\u30A4\u30E0\u30A2\u30A6\u30C8"));
        this.close();
      }, 8e3);
      this.ws.onopen = () => {
        window.clearTimeout(timer);
        resolve();
      };
      this.ws.onerror = () => {
        window.clearTimeout(timer);
        reject(new Error("\u63A5\u7D9A\u30A8\u30E9\u30FC"));
      };
      this.ws.onclose = () => {
        var _a, _b;
        (_b = (_a = this.handlers).onClose) == null ? void 0 : _b.call(_a);
      };
      this.ws.onmessage = (ev) => {
        if (typeof ev.data !== "string")
          return;
        let msg;
        try {
          msg = JSON.parse(ev.data);
        } catch (e) {
          return;
        }
        this.dispatch(msg);
      };
    });
  }
  dispatch(msg) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    switch (msg.type) {
      case "ready":
        (_b = (_a = this.handlers).onReady) == null ? void 0 : _b.call(_a);
        break;
      case "partial":
        (_d = (_c = this.handlers).onPartial) == null ? void 0 : _d.call(_c);
        break;
      case "chunk":
        if (msg.text)
          (_f = (_e = this.handlers).onChunk) == null ? void 0 : _f.call(_e, msg.text);
        break;
      case "reconvert":
        (_h = (_g = this.handlers).onReconvert) == null ? void 0 : _h.call(_g, msg);
        break;
      case "error":
        (_j = (_i = this.handlers).onError) == null ? void 0 : _j.call(_i, msg.message || "unknown error");
        break;
    }
  }
  sendAudio(pcm16) {
    if (this.connected)
      this.ws.send(pcm16);
  }
  sendStart(stripSpace, symbols) {
    this.send({ type: "start", stripSpace, symbols });
  }
  sendStop() {
    this.send({ type: "stop" });
  }
  sendReconvert(text) {
    this.send({ type: "reconvert", text });
  }
  send(obj) {
    if (this.connected)
      this.ws.send(JSON.stringify(obj));
  }
  close() {
    if (this.ws) {
      this.ws.onclose = null;
      try {
        this.ws.close();
      } catch (e) {
      }
      this.ws = null;
    }
  }
};

// anchor.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var setAnchorEffect = import_state.StateEffect.define();
var AnchorWidget = class extends import_view.WidgetType {
  eq() {
    return true;
  }
  toDOM() {
    const el = document.createElement("span");
    el.className = "voxcraft-anchor";
    el.setAttribute("aria-hidden", "true");
    return el;
  }
  ignoreEvent() {
    return true;
  }
};
var anchorField = import_state.StateField.define({
  create() {
    return null;
  },
  update(value, tr) {
    for (const e of tr.effects) {
      if (e.is(setAnchorEffect))
        return e.value;
    }
    if (value !== null && tr.docChanged) {
      return tr.changes.mapPos(value, 1);
    }
    return value;
  }
});
var anchorDecorations = import_view.EditorView.decorations.compute([anchorField], (state) => {
  const pos = state.field(anchorField, false);
  if (pos === null || pos === void 0)
    return import_view.Decoration.none;
  const at = Math.max(0, Math.min(pos, state.doc.length));
  return import_view.Decoration.set([
    import_view.Decoration.widget({ widget: new AnchorWidget(), side: 1 }).range(at)
  ]);
});
var anchorExtension = [anchorField, anchorDecorations];
function setAnchor(cm, pos) {
  cm.dispatch({ effects: setAnchorEffect.of(pos) });
}
function clearAnchor(cm) {
  cm.dispatch({ effects: setAnchorEffect.of(null) });
}
function getAnchor(cm) {
  const v = cm.state.field(anchorField, false);
  return v === void 0 ? null : v;
}

// main.ts
var VoxCraftPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.socket = null;
    this.recorder = null;
    this.recording = false;
    // 口述対象として録音開始時に固定するエディタ（背面作業やノート切替の影響を受けない）。
    this.cm = null;
    // アンカーに追記したチャンク列（取り消し・変換戻しの対象特定に使う。アンカー相対）。
    this.chunks = [];
    // 変換戻しの応答が返るまで対象範囲を覚えておく。
    this.pendingReconvert = null;
    this.reconvertModal = null;
    // 入力レベルメーター表示のスロットリング用。
    this.lastMeterAt = 0;
    this.transcribing = false;
  }
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(anchorExtension);
    this.ribbonEl = this.addRibbonIcon("mic", "VoxCraft \u97F3\u58F0\u5165\u529B\u306E\u958B\u59CB/\u505C\u6B62", () => {
      this.toggleRecording();
    });
    this.statusEl = this.addStatusBarItem();
    this.setStatus("\u505C\u6B62\u4E2D");
    this.addCommand({
      id: "toggle-recording",
      name: "\u97F3\u58F0\u5165\u529B\u306E\u958B\u59CB/\u505C\u6B62",
      callback: () => this.toggleRecording()
    });
    this.addCommand({
      id: "stop-recording",
      name: "\u97F3\u58F0\u5165\u529B\u3092\u505C\u6B62",
      callback: () => this.stopRecording()
    });
    this.addCommand({
      id: "reconvert-last",
      name: "\u76F4\u524D\u306E\u5165\u529B\u3092\u5909\u63DB\u623B\u3057",
      callback: () => this.requestReconvert()
    });
    this.addSettingTab(new VoxCraftSettingTab(this.app, this));
  }
  async onunload() {
    await this.teardownSession();
  }
  // ---- 録音セッション制御 ----
  toggleRecording() {
    if (this.recording)
      this.stopRecording();
    else
      void this.startRecording();
  }
  async startRecording() {
    if (this.recording)
      return;
    const cm = this.getActiveCm();
    if (!cm) {
      new import_obsidian3.Notice("VoxCraft: \u633F\u5165\u5148\u306E\u30CE\u30FC\u30C8\uFF08\u7DE8\u96C6\u30E2\u30FC\u30C9\uFF09\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    this.setStatus("\u63A5\u7D9A\u4E2D\u2026");
    this.socket = new AsrSocket(this.settings.serverUrl, {
      onReady: () => this.setStatus("\u5F85\u6A5F\u4E2D\u2026 \u8A71\u3057\u3066\u304F\u3060\u3055\u3044"),
      onPartial: () => {
        this.transcribing = true;
        this.setStatus("\u8A8D\u8B58\u4E2D\u2026");
      },
      onChunk: (text) => {
        this.transcribing = false;
        this.handleChunk(text);
      },
      onReconvert: (msg) => this.handleReconvert(msg),
      onError: (m) => new import_obsidian3.Notice(`VoxCraft \u30B5\u30FC\u30D0\u30FC\u30A8\u30E9\u30FC: ${m}`),
      onClose: () => {
        if (this.recording) {
          new import_obsidian3.Notice("VoxCraft: \u30B5\u30FC\u30D0\u30FC\u63A5\u7D9A\u304C\u5207\u308C\u307E\u3057\u305F\u3002");
          void this.teardownSession();
          this.setStatus("\u505C\u6B62\u4E2D");
        }
      }
    });
    try {
      await this.socket.connect();
    } catch (e) {
      new import_obsidian3.Notice(
        `VoxCraft: \u30B5\u30FC\u30D0\u30FC\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093\uFF08${this.settings.serverUrl}\uFF09\u3002\u8A8D\u8B58\u30B5\u30FC\u30D0\u30FC\u304C\u8D77\u52D5\u3057\u3066\u3044\u308B\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002`
      );
      this.socket = null;
      this.setStatus("\u505C\u6B62\u4E2D");
      return;
    }
    this.socket.sendStart(
      this.settings.stripJaAlnumSpace,
      this.settings.symbolDictation
    );
    this.recorder = new MicRecorder(
      (pcm) => {
        var _a;
        return (_a = this.socket) == null ? void 0 : _a.sendAudio(pcm);
      },
      (level) => this.showLevel(level)
    );
    try {
      await this.recorder.start();
    } catch (e) {
      new import_obsidian3.Notice("VoxCraft: \u30DE\u30A4\u30AF\u306B\u30A2\u30AF\u30BB\u30B9\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
      await this.teardownSession();
      this.setStatus("\u505C\u6B62\u4E2D");
      return;
    }
    this.cm = cm;
    this.chunks = [];
    this.pendingReconvert = null;
    setAnchor(cm, cm.state.selection.main.head);
    this.recording = true;
    this.ribbonEl.addClass("voxcraft-recording");
    this.setStatus("\u25CF \u9332\u97F3\u4E2D");
  }
  stopRecording() {
    var _a, _b;
    if (!this.recording)
      return;
    this.recording = false;
    this.ribbonEl.removeClass("voxcraft-recording");
    this.setStatus("\u505C\u6B62\u51E6\u7406\u4E2D\u2026");
    (_a = this.socket) == null ? void 0 : _a.sendStop();
    void ((_b = this.recorder) == null ? void 0 : _b.stop().then(() => {
      this.recorder = null;
    }));
    window.setTimeout(() => {
      var _a2;
      (_a2 = this.socket) == null ? void 0 : _a2.close();
      this.socket = null;
      this.clearDictationAnchor();
      this.setStatus("\u505C\u6B62\u4E2D");
    }, 1500);
  }
  async teardownSession() {
    var _a, _b, _c;
    this.recording = false;
    (_a = this.ribbonEl) == null ? void 0 : _a.removeClass("voxcraft-recording");
    await ((_b = this.recorder) == null ? void 0 : _b.stop());
    this.recorder = null;
    (_c = this.socket) == null ? void 0 : _c.close();
    this.socket = null;
    this.clearDictationAnchor();
  }
  clearDictationAnchor() {
    if (this.cm && this.cm.dom.isConnected)
      clearAnchor(this.cm);
    this.cm = null;
  }
  // ---- 確定チャンクの処理 ----
  handleChunk(text) {
    if (this.settings.enableCommands) {
      const cmd = parseCommand(text, this.settings.commandPrefix);
      if (cmd) {
        this.runCommand(cmd);
        return;
      }
    }
    this.insertText(text);
  }
  runCommand(cmd) {
    switch (cmd.kind) {
      case "stop":
        this.stopRecording();
        break;
      case "undo":
        this.undoLast();
        break;
      case "newline":
        this.insertText("\n");
        break;
      case "reconvert":
        this.requestReconvert();
        break;
      case "replace":
        this.replaceInDoc(cmd.from, cmd.to);
        break;
      case "pick":
        if (this.reconvertModal)
          this.reconvertModal.pickByVoice(cmd.index);
        break;
    }
  }
  // アンカー位置に追記する。ユーザーが手動でカーソルを離していれば、
  // その編集位置は動かさず（follow=false）、アンカーにだけ差し込む。
  insertText(text) {
    const cm = this.cm;
    if (!cm || !cm.dom.isConnected)
      return;
    const anchor = getAnchor(cm);
    if (anchor === null)
      return;
    const at = Math.min(anchor, cm.state.doc.length);
    const follow = cm.state.selection.main.head === anchor;
    cm.dispatch({
      changes: { from: at, to: at, insert: text },
      selection: follow ? { anchor: at + text.length } : void 0,
      scrollIntoView: follow
    });
    this.chunks.push(text);
    if (this.chunks.length > 200)
      this.chunks.shift();
  }
  // 直前チャンク（アンカー直前の text.length 文字）を削除する。
  undoLast() {
    const cm = this.cm;
    const last = this.chunks[this.chunks.length - 1];
    if (!cm || last === void 0)
      return;
    const anchor = getAnchor(cm);
    if (anchor === null)
      return;
    const from = Math.max(0, anchor - last.length);
    const current = cm.state.doc.sliceString(from, anchor);
    if (current !== last) {
      new import_obsidian3.Notice("VoxCraft: \u76F4\u524D\u306E\u5165\u529B\u304C\u7DE8\u96C6\u3055\u308C\u3066\u3044\u308B\u305F\u3081\u53D6\u308A\u6D88\u305B\u307E\u305B\u3093\u3002");
      return;
    }
    this.chunks.pop();
    cm.dispatch({ changes: { from, to: anchor, insert: "" } });
  }
  // 「AをBに修正」: ノート全体からAをBに置換（過去テキストも対象）。
  replaceInDoc(from, to) {
    var _a;
    const cm = (_a = this.cm) != null ? _a : this.getActiveCm();
    if (!cm)
      return;
    const doc = cm.state.doc.toString();
    const idx = doc.lastIndexOf(from);
    if (idx < 0) {
      new import_obsidian3.Notice(`VoxCraft: \u300C${from}\u300D\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F\u3002`);
      return;
    }
    cm.dispatch({ changes: { from: idx, to: idx + from.length, insert: to } });
  }
  // ---- 変換戻し ----
  requestReconvert() {
    var _a;
    const cm = this.cm;
    const last = this.chunks[this.chunks.length - 1];
    if (!cm || !cm.dom.isConnected) {
      new import_obsidian3.Notice("VoxCraft: \u9332\u97F3\u4E2D\u306B\u300C\u5909\u63DB\u623B\u3057\u300D\u3092\u4F7F\u3063\u3066\u304F\u3060\u3055\u3044\u3002");
      return;
    }
    const anchor = getAnchor(cm);
    if (anchor === null || last === void 0 || !last.trim()) {
      new import_obsidian3.Notice("VoxCraft: \u5909\u63DB\u623B\u3057\u306E\u5BFE\u8C61\u304C\u3042\u308A\u307E\u305B\u3093\u3002");
      return;
    }
    if (!((_a = this.socket) == null ? void 0 : _a.connected)) {
      new import_obsidian3.Notice("VoxCraft: \u30B5\u30FC\u30D0\u30FC\u672A\u63A5\u7D9A\u306E\u305F\u3081\u5909\u63DB\u623B\u3057\u3067\u304D\u307E\u305B\u3093\u3002");
      return;
    }
    const from = Math.max(0, anchor - last.length);
    const targetText = cm.state.doc.sliceString(from, anchor);
    this.pendingReconvert = { from, to: anchor };
    this.socket.sendReconvert(targetText);
    this.setStatus("\u5909\u63DB\u5019\u88DC\u3092\u53D6\u5F97\u4E2D\u2026");
  }
  handleReconvert(msg) {
    this.setStatus(this.recording ? "\u25CF \u9332\u97F3\u4E2D" : "\u505C\u6B62\u4E2D");
    const segments = msg.segments || [];
    const target = this.pendingReconvert;
    this.pendingReconvert = null;
    if (segments.length === 0 || !target) {
      new import_obsidian3.Notice("VoxCraft: \u5909\u63DB\u5019\u88DC\u304C\u5F97\u3089\u308C\u307E\u305B\u3093\u3067\u3057\u305F\u3002");
      return;
    }
    const modal = new ReconvertModal(this.app, segments, (chosen) => {
      this.applyReconvert(target, chosen.join(""));
    });
    const origClose = modal.onClose.bind(modal);
    modal.onClose = () => {
      origClose();
      if (this.reconvertModal === modal)
        this.reconvertModal = null;
    };
    this.reconvertModal = modal;
    modal.open();
  }
  applyReconvert(target, newText) {
    var _a;
    const cm = (_a = this.cm) != null ? _a : this.getActiveCm();
    if (!cm)
      return;
    const to = Math.min(target.to, cm.state.doc.length);
    const from = Math.min(target.from, to);
    cm.dispatch({ changes: { from, to, insert: newText } });
    if (this.chunks.length > 0)
      this.chunks[this.chunks.length - 1] = newText;
  }
  // ---- ユーティリティ ----
  // アクティブな Markdown エディタの CodeMirror6 ビューを得る。
  getActiveCm() {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const editor = view == null ? void 0 : view.editor;
    return (_a = editor == null ? void 0 : editor.cm) != null ? _a : null;
  }
  // 入力レベルをステータスバーにメーター表示（音声を拾えているかの確認用）。
  showLevel(level) {
    if (!this.recording || this.transcribing)
      return;
    const now = performance.now();
    if (now - this.lastMeterAt < 100)
      return;
    this.lastMeterAt = now;
    const segs = 10;
    const filled = Math.max(0, Math.min(segs, Math.round(level * 40)));
    const bar = "\u2588".repeat(filled) + "\u2591".repeat(segs - filled);
    this.setStatus(`\u25CF \u9332\u97F3\u4E2D ${bar}`);
  }
  setStatus(text) {
    this.statusEl.setText(`\u{1F399} VoxCraft: ${text}`);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
