import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";

const prod = (process.argv[2] === "production");

// 出力先（Vault の plugins フォルダ）。環境変数 OBSIDIAN_PLUGIN_DIR で上書き可。
const defaultDir = "G:/マイドライブ/Software/Obsidian/Obsidian Vault/.obsidian/plugins/voxcraft";
const dir = process.env.OBSIDIAN_PLUGIN_DIR || defaultDir;

if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
}

const context = await esbuild.context({
    banner: {
        js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nif you want to view the source, please visit the github repository of this plugin.\n*/',
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: path.join(dir, "main.js"),
});

const copyFiles = () => {
    try {
        fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
        if (fs.existsSync("styles.css")) {
            fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
        }
        console.log("✨ Copied manifest.json / styles.css to destination.");
    } catch (e) {
        console.error("Failed to copy static files:", e);
    }
};

if (prod) {
    await context.rebuild();
    copyFiles();
    process.exit(0);
} else {
    await context.watch();
    copyFiles();
}
